export const skillsData = {
    'HTML': 'nonicons:html-16',
    'CSS': 'nonicons:css-16',
    'C': 'mdi:language-c',
    'SQL': 'tabler:sql',
    'JavaScript': 'fluent:code-js-16-filled',
    'Python': 'proicons:python',
    'React': 'mdi:react',
    'Nextjs': 'tabler:brand-nextjs',
    'Express': 'simple-icons:express',
    'Tailwind': 'teenyicons:tailwind-outline',
    'Redux': 'file-icons:redux',
    'Material UI': 'mdi:material-ui',
    'Bootstrap': 'hugeicons:bootstrap',
    'Github': 'line-md:github',
    'PostgreSQL': 'simple-icons:postgresql',
    'Supabase': 'ri:supabase-fill',
    'Insomnia': 'devicon-plain:insomnia',
    'Figma': 'solar:figma-outline',
    'Slack': 'mdi:slack',
    'Trello': 'hugeicons:trello',
    'Illustrator': 'hugeicons:adobe-illustrator',
    'NodeJS': 'lineicons:nodejs'
}